### ISSUE TITLE
I got a challenge to get mario into danger I did so then leveled up on the fight and the item didnt drop

### ISSUE THREAD

**Issue by Ss3nm0dn4r** [jdaster64/ttyd-infinite-pit#2]

**Comment by jdaster64** [comment]
This issue has been reported on my Discord server; will probably fix next patch.

**Comment by jdaster64** [comment]
Should be fixed in v1.03; note, as a result, you can no longer rely on a level-up to fully heal you for the "finish with more than X HP" condition.

**Comment by jdaster64** [comment]
Condition rewards are broken in general in v1.03; will try to look into a fix later

**Comment by jdaster64** [comment]
Fixed in v1.03.1.
