### ISSUE TITLE
Overworld enemy doesn't despawn if Bandit flees fight

### ISSUE THREAD

**Issue by redyoshi49q** [jdaster64/ttyd-infinite-pit#4]
I don't know whether this is intended behavior or not because of the changelog entries, but I'm creating an issue for it in case it's not intended.

If you complete a fight where a Bandit escapes with loot, the player is awarded Star Points for defeated enemies, but the overworld creature is _not_ despawned, and the battle can (and, in fact, must) be fought again.  This can allow for a player to use that battle to repeatedly farm for star points.

In such a case, it would make sense for either the overworld creature to despawn or for the combat to be modified such that it only includes the fled Bandits (in order to prevent Star Point farming).

**Comment by jdaster64** [comment]
Not a bug, works that way in vanilla.
