### ISSUE TITLE
Bandit loot overrides Bandit's held item/badge

### ISSUE THREAD

**Issue by redyoshi49q** [jdaster64/ttyd-infinite-pit#5]
If a Bandit holding a badge succeeds at stealing a coin from the player, the coin seems to override the Bandit's held badge (presumably, this is also true of held items that have yet to be used).  Ms. Mowz can steal from that bandit, but doing so steals the coin, leaving a Bandit with no badge.

**Comment by jdaster64** [comment]
Not a bug, works that way in vanilla.  You might still get the badge it used to be holding as a drop, too, provided you don't steal the stolen item back rather than defeating the Bandit to hold it naturally.
