### ISSUE TITLE
SUGGESTION: Charge Badge adjustment

### ISSUE THREAD

**Issue by Spyrois2cool** [jdaster64/ttyd-infinite-pit#7]
Would it reasonable to request Charge badges to be changed so that each extra badge/level adds +2 attack instead of +1? I think its kinda disappointing to have each additional charge to only add +1 damage. I think it would also have them see more use.

**Comment by jdaster64** [comment]
I'm not making further balance adjustments to the game at this point; Charge +3 is already strong enough with multi-hits that I wouldn't want getting +4 to be that attainable anyway.
